name: Release
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.spec.js'
      - '.idea'
      - '.gitignore'
      - '.github/**'
      - '!.github/workflows/release.yml'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.spec.js'
      - '.idea'
      - '.gitignore'
      - '.github/**'
      - '!.github/workflows/release.yml'

jobs:
  build-macos:
    name: Build macOS binary (dmg)
    runs-on: macos-latest
    timeout-minutes: 60

    env:
      USE_HARD_LINKS: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Update NPM
        run: |
          npm install -g npm@latest
      - name: Get version from package.json
        id: app-version
        run: |
          PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
          echo "::set-output name=PACKAGE_VERSION::$PACKAGE_VERSION"
      - name: Bundle and package application
        run: |
          npm ci
          npm run precompile
          npm run package:mac
      - name: Get binary shasum
        run: |
          shasum -a 256 ./dist/laravel-sqlens.setup.${{steps.app-version.outputs.PACKAGE_VERSION}}.dmg
      - name: Upload macOS dmg
        uses: actions/upload-artifact@v1
        with:
          name: dmg
          path: ./dist/laravel-sqlens.setup.${{steps.app-version.outputs.PACKAGE_VERSION}}.dmg

  build-linux:
    name: Build Linux binaries (deb, rpm, snap, AppImage)
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      USE_HARD_LINKS: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Update NPM
        run: |
          npm install -g npm@latest
      - name: Get version from package.json
        id: app-version
        run: |
          PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
          echo "::set-output name=PACKAGE_VERSION::$PACKAGE_VERSION"
      - name: Bundle and package application
        run: |
          npm ci
          npm run precompile
          npm run package:linux
      - name: Upload Linux AppImage
        uses: actions/upload-artifact@v1
        with:
          name: appimage
          path: ./dist/laravel-sqlens-${{steps.app-version.outputs.PACKAGE_VERSION}}.AppImage
      - name: Upload Linux deb
        uses: actions/upload-artifact@v1
        with:
          name: deb
          path: ./dist/laravel-sqlens-${{steps.app-version.outputs.PACKAGE_VERSION}}.deb
      - name: Upload Linux rpm
        uses: actions/upload-artifact@v1
        with:
          name: rpm
          path: ./dist/laravel-sqlens-${{steps.app-version.outputs.PACKAGE_VERSION}}.rpm
      - name: Upload Linux snap
        uses: actions/upload-artifact@v1
        with:
          name: snap
          path: ./dist/laravel-sqlens-${{steps.app-version.outputs.PACKAGE_VERSION}}.snap

  build-windows:
    name: Build Windows binary (exe)
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Update NPM
        run: |
          npm install -g npm@latest
      - name: Get version from package.json
        id: app-version
        run: |
          $PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
          echo "::set-output name=PACKAGE_VERSION::$PACKAGE_VERSION"
        shell: pwsh
      - name: Bundle and package application
        run: |
          npm ci
          npm run precompile
          npm run package:win
        shell: pwsh
      - name: Upload Windows setup exe
        uses: actions/upload-artifact@v1
        with:
          name: exe
          path: ./dist/laravel-sqlens.setup.${{steps.app-version.outputs.PACKAGE_VERSION}}.exe
      - name: Upload Windows portable exe
        uses: actions/upload-artifact@v1
        with:
          name: exe
          path: ./dist/laravel-sqlens.portable.${{steps.app-version.outputs.PACKAGE_VERSION}}.exe
